print("hello nama saya : Nursyah \n umur sayah :18 \t tapi boong \n agama saya : islam")
nama = input(" nama kamu siapa bosque???? ")
umur = input(" umurmu berapa bosque??? ")
Suka = input(" hehehe nikmat kan rasanya!! ")
tidak = input (" hehehe sama dong ")
print(" wiiih salam kenal ya bossque "+ nama +" \n kamu sudah "+ umur +" tahun ")
